name: Docker Image CI

on:
  push:

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: login in amazon ecr
      run: (Get-ECRLoginCommand).Password | docker login --username AWS --password-stdin 661869326354.dkr.ecr.us-east-1.amazonaws.com

    - name: create image
      run: docker build -t endterm-sdu

    - name: tag image
      run: docker tag endterm-sdu:latest 661869326354.dkr.ecr.us-east-1.amazonaws.com/endterm-sdu:latest

    - name: push
      run: docker push 661869326354.dkr.ecr.us-east-1.amazonaws.com/endterm-sdu:latest

